---
title: "CodeBook.md"
author: "JH"
date: "2025-10-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Code Book for independent_dataset.txt

This is a code book for the final data set saved as independent_dataset.txt, as created through run_analysis.R.

Each record of the independent_dataset.txt table is identified with two variables:

-   subject - a number that identifies the subject who performed the activity for each window sample. Its range is from 1 to 30.

-   activity - the activity the subject was performing at the time of the measurements. It has six levels:

    -   WALKING: subject walking

    -   WALKING_UPSTAIRS: subject climbing stairs at a walking pace

    -   WALKING_DOWNSTAIRS: subject descending stairs at a walking pace

    -   SITTING: subject sitting down

    -   STANDING: subject standing up

    -   LAYING: subject lying down

The subsequent variables are the means (Mean) and standard deviations (Std) of each measurement taken on the X, Y , and Z (X, Y, or Z) axes for each subject during each activity. They are normalized and bounded within [-1,1]:

-   tBodyAccMeanX

-   tBodyAccMeanY

-   tBodyAccMeanZ

-   tBodyAccStdX

-   tBodyAccStdY

-   tBodyAccStdZ

-   tGravityAccMeanX

-   tGravityAccMeanY

-   tGravityAccMeanZ

-   tGravityAccStdX

-   tGravityAccStdY

-   tGravityAccStdZ

-   tBodyAccJerkMeanX

-   tBodyAccJerkMeanY

-   tBodyAccJerkMeanZ

-   tBodyAccJerkStdX

-   tBodyAccJerkStdY

-   tBodyAccJerkStdZ

-   tBodyGyroMeanX

-   tBodyGyroMeanY

-   tBodyGyroMeanZ

-   tBodyGyroStdX

-   tBodyGyroStdY

-   tBodyGyroStdZ

-   tBodyGyroJerkMeanX

-   tBodyGyroJerkMeanY

-   tBodyGyroJerkMeanZ

-   tBodyGyroJerkStdX

-   tBodyGyroJerkStdY

-   tBodyGyroJerkStdZ

-   tBodyAccMagMean

-   tBodyAccMagStd

-   tGravityAccMagMean

-   tGravityAccMagStd

-   tBodyAccJerkMagMean

-   tBodyAccJerkMagStd

-   tBodyGyroMagMean

-   tBodyGyroMagStd

-   tBodyGyroJerkMagMean

-   tBodyGyroJerkMagStd

-   fBodyAccMeanX

-   fBodyAccMeanY

-   fBodyAccMeanZ

-   fBodyAccStdX

-   fBodyAccStdY

-   fBodyAccStdZ

-   fBodyAccMeanFreqX

-   fBodyAccMeanFreqY

-   fBodyAccMeanFreqZ

-   fBodyAccJerkMeanX

-   fBodyAccJerkMeanY

-   fBodyAccJerkMeanZ

-   fBodyAccJerkStdX

-   fBodyAccJerkStdY

-   fBodyAccJerkStdZ

-   fBodyAccJerkMeanFreqX

-   fBodyAccJerkMeanFreqY

-   fBodyAccJerkMeanFreqZ

-   fBodyGyroMeanX

-   fBodyGyroMeanY

-   fBodyGyroMeanZ

-   fBodyGyroStdX

-   fBodyGyroStdY

-   fBodyGyroStdZ

-   fBodyGyroMeanFreqX

-   fBodyGyroMeanFreqY

-   fBodyGyroMeanFreqZ

-   fBodyAccMagMean

-   fBodyAccMagStd

-   fBodyAccMagMeanFreq

-   fBodyBodyAccJerkMagMean

-   fBodyBodyAccJerkMagStd

-   fBodyBodyAccJerkMagMeanFreq

-   fBodyBodyGyroMagMean

-   fBodyBodyGyroMagStd

-   fBodyBodyGyroMagMeanFreq

-   fBodyBodyGyroJerkMagMean

-   fBodyBodyGyroJerkMagStd

-   fBodyBodyGyroJerkMagMeanFreq
